### ISSUE TITLE
Old Dependencies

### ISSUE THREAD

**Issue by nietsmmar** [gabrielpatricksouza/webviewimage#1]
I am having the problem that I can't upgrade my supabase dependencies because this package still uses `webview_flutter<4.0.0`

`supabase_flutter >=1.7.0 depends on webview_flutter ^4.0.0 and webviewimage >=0.0.2 depends on webview_flutter ^3.0.4`

**Comment by gabrielpatricksouza** [comment]
Sorry, I hadn't uploaded all the changes, access the latest version, v2.5.4
